const express = require("express");
const router = express.Router();
const authControllers = require("../controllers/auth-controller");
const auth = require("../middlewares/validate-middleware");
const authMiddleware = require("../middlewares/auth-middleware");
const signUpSchema = require("../validators/auth-validator");
router.route("/").get(authControllers.home);
router.route("/register").post(auth(signUpSchema), authControllers.register);
router.route("/login").post(authControllers.login);
router.route("/user").get(authMiddleware, authControllers.user);
module.exports = router;
